// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbowK6aOC8UcN1g5hWVEtQYOkkTOJJSDQ',
    appId: '1:772206302274:web:8cf69d08a82378cacb89db',
    messagingSenderId: '772206302274',
    projectId: 'taxiapp-e5f40',
    authDomain: 'taxiapp-e5f40.firebaseapp.com',
    databaseURL: 'https://taxiapp-e5f40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxiapp-e5f40.firebasestorage.app',
    measurementId: 'G-J56NBH5W9H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOw6-gdNIw_E6GDl7HWb2eN2CK8xgawVQ',
    appId: '1:772206302274:ios:cca4acdd0ef66665cb89db',
    messagingSenderId: '772206302274',
    projectId: 'taxiapp-e5f40',
    databaseURL: 'https://taxiapp-e5f40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxiapp-e5f40.firebasestorage.app',
    iosBundleId: 'com.example.taxiAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOw6-gdNIw_E6GDl7HWb2eN2CK8xgawVQ',
    appId: '1:772206302274:ios:cca4acdd0ef66665cb89db',
    messagingSenderId: '772206302274',
    projectId: 'taxiapp-e5f40',
    databaseURL: 'https://taxiapp-e5f40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxiapp-e5f40.firebasestorage.app',
    iosBundleId: 'com.example.taxiAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbowK6aOC8UcN1g5hWVEtQYOkkTOJJSDQ',
    appId: '1:772206302274:web:775b55f086f604eccb89db',
    messagingSenderId: '772206302274',
    projectId: 'taxiapp-e5f40',
    authDomain: 'taxiapp-e5f40.firebaseapp.com',
    databaseURL: 'https://taxiapp-e5f40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxiapp-e5f40.firebasestorage.app',
    measurementId: 'G-GTCDP4SNFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpdirSoJZWkylGffmMEkPmoxFY9PzZBL8',
    appId: '1:772206302274:android:d829981ad77632b8cb89db',
    messagingSenderId: '772206302274',
    projectId: 'taxiapp-e5f40',
    databaseURL: 'https://taxiapp-e5f40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxiapp-e5f40.firebasestorage.app',
  );

}